services:
  _defaults:
    autowire: true
    autoconfigure: true
  color_picker_custom:
    class: SevenGroupFrance\SuluColorPickerBundle\Content\Types\ColorPickerCustom
    tags: [{ name: "sulu.content.type", alias: "color_picker_custom" }]
